version: "2.1"
services:

  backend:
    image: zhongdj/git-stats-backend:v0.95
    ports:
      - "9000:9000"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.git-stats-tasks:/root/.tasks
      - ~/tags:/root/tags
      - ~/metabase:/opt/docker/conf/metabase
    depends_on:
      db:
        condition: service_healthy
      metabase:
        condition: service_healthy
          

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r5t
      - LANG=en_US.UTF-8
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p1q2w3e4r5t"]
      timeout: 20s
      retries: 10
 
  metabase:
    image:  metabase/metabase:v0.35.4
    ports:
      - "3000:3000" 
    healthcheck:
      test: ["CMD", "wget", "http://localhost:3000"]
      timeout: 20s
      retries: 10
