version: "2.1"
services:

  backend:
    image: zhongdj/git-stats-backend:v0.994
    ports:
      - "9000:9000"
      - "5005:5005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~/.git-stats-tasks:/root/.tasks
      - ~/tags:/root/tags
    depends_on:
      db:
        condition: service_healthy
      metabase:
        condition: service_healthy

  golang-qa:
    image: zhongdj/golang-qa:v0.1
    volumes:
      - ~/.git-stats-tasks:/root/.tasks
    command: ["ping", "-i", "100", "golang-qa"]
          

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r5t
      - LANG=en_US.UTF-8
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p1q2w3e4r5t"]
      timeout: 20s
      retries: 10
 
  metabase:
    image:  metabase/metabase:v0.35.4
    ports:
      - "3000:3000" 
    healthcheck:
      test: ["CMD", "wget", "http://localhost:3000"]
      timeout: 5s
      retries: 20
